name: logique_mobile_developer_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # network
  http: ^1.1.0

  # dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.1

  # database
  sqflite: ^2.3.0

  # utils
  intl: ^0.18.1
  path: ^1.8.3

  # state management
  flutter_bloc: ^8.1.3

  # ui
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
